### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by kmulvey** [aaronm67/node-phash#14]
this is really the same as #11 except the problem has nothing to do with #include, its not a comment nor is it intended to be:

```
kmulvey@dirtwolf: similar > npm install phash
npm http GET https://registry.npmjs.org/phash
npm http 200 https://registry.npmjs.org/phash
npm http GET https://registry.npmjs.org/phash/-/phash-0.0.5.tgz
npm http 200 https://registry.npmjs.org/phash/-/phash-0.0.5.tgz

> phash@0.0.5 install /opt/code/similar/node_modules/phash
> node-gyp rebuild

make: Entering directory '/opt/code/similar/node_modules/phash/build'
  CXX(target) Release/obj.target/pHash/phash.o
../phash.cpp:3:19: fatal error: pHash.h: No such file or directory
 #include <pHash.h>
                   ^
compilation terminated.
pHash.target.mk:84: recipe for target 'Release/obj.target/pHash/phash.o' failed
make: *** [Release/obj.target/pHash/phash.o] Error 1
make: Leaving directory '/opt/code/similar/node_modules/phash/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.0.0-rc1+
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/code/similar/node_modules/phash
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by kmulvey** [comment]
totally my fault, need to install libphash, libphash-devel, CImg-devel

**Comment by niallatbynder** [comment]
Hey kmulvey,

Could you say how to install libphash and the others? (This seems to be such basic knowledge that nobody bothers to write it down) :P 

Thanks!

**Comment by aaronm67** [comment]
What operating system are you on?

On a Mac, you install Macports (https://www.macports.org/) then : `ports install phash`
On a debian server, you can follow along here: http://www.cybercrimetech.com/2013/06/how-to-install-phash-on-ubuntu.html

**Comment by niallatbynder** [comment]
Ubuntu trusty. I need to be able to automate the install in Dockerfile so it needs to be the command line :P

**Comment by aaronm67** [comment]
I think this will also work:

https://launchpad.net/ubuntu/+source/libphash

So just `apt-get install libphash`

**Comment by niallatbynder** [comment]
That was the first thing I tired. It seems to be a core package but doesn't come with trusty. I think that means it can't be installed via apt as usual

**Comment by niallatbynder** [comment]
Got it! `apt-cache search libphash` returned the actual package name... libphash0
So `apt-get install libphash0`
Thanks for the help but FML
