### ISSUE TITLE
Implement all of Phash Functionality

### ISSUE THREAD

**Issue by aaronm67** [aaronm67/node-phash#2]
I'd like to provide an interface similar to the ruby phash bindings,

http://rubydoc.info/gems/pHash/1.1.1/Phash

the remaining methods to include are:

```
ph_audiohash(PATH)

ph_audio_distance_ber(hash1, hash2)

ph_hamming_distance(hash1, hash2)

ph_texthash(PATH)

ph_dct_videohash_dist(hash1, hash2)

ph_dct_videohash(PATH)
```

**Comment by srameshr** [comment]
@skhvan1111 @aaronm67 Wow, Im really late into this post, but did you guys end up including support for this?
Now, gifs are everywhere, so supporting gif would seem a great boost.
